import { use } from "react";

// This page is intentionally plain text — readable by LLMs, scrapers, and search engines.
// It auto-generates alongside every investor profile.

export default function ForLLM({ params }: { params: Promise<{ handle: string }> }) {
  const { handle } = use(params);

  // TODO: fetch real data from Supabase by handle
  const data = {
    name: "Alex Farcet",
    handle: handle,
    firm: "Raspberry Ventures",
    location: "Lisbon & UK",
    updated: new Date().toISOString().split("T")[0],
    ticket_min: 50000,
    ticket_max: 650000,
    stages: ["Seed", "Early Series A"],
    sectors: ["ClimateTech", "Applied AI"],
    geographies: ["Europe", "Israel", "Africa", "US (select)"],
    wont_invest_in: "Pre-seed / idea stage, consumer apps, crypto, gaming, pre-revenue",
    how_we_work: "Co-invest via single SPV (Odin). One cap-table line, one signature. Founder-friendly, no governance overhead. Community of 200+ engaged private investors.",
    apply_url: `https://scopecheck.ai/${handle}/apply`,
    profile_url: `https://scopecheck.ai/${handle}`,
  };

  const text = `SCOPECHECK INVESTOR PROFILE
===========================
Name: ${data.name}
Firm: ${data.firm}
Handle: ${data.handle}
Location: ${data.location}
Last updated: ${data.updated}

INVESTMENT CRITERIA
-------------------
Ticket size: €${(data.ticket_min / 1000).toFixed(0)}K – €${(data.ticket_max / 1000).toFixed(0)}K (via single SPV)
Stage: ${data.stages.join(", ")}
Sectors: ${data.sectors.join(", ")}
Geography: ${data.geographies.join(", ")}
Will not invest in: ${data.wont_invest_in}

HOW WE WORK
-----------
${data.how_we_work}

LINKS
-----
Apply: ${data.apply_url}
Full profile: ${data.profile_url}

---
This page is machine-readable and auto-generated by ScopeCheck.
Human-readable profile: ${data.profile_url}
`;

  return (
    <pre style={{
      fontFamily: "DM Mono, monospace",
      fontSize: "0.82rem",
      lineHeight: 1.7,
      color: "#cbd5e1",
      background: "#0a0f1e",
      padding: "2rem",
      minHeight: "100vh",
      margin: 0,
      whiteSpace: "pre-wrap",
      wordBreak: "break-word",
    }}>
      {text}
    </pre>
  );
}
